@startuml
start
:管理画面表示;
:商品一覧表示;
:管理メニュー表示;
:管理コード入力;
if (管理コードは1) then (yes)
  :売上リセット;
  :商品リスト更新;
elseif (管理コードは2) then (yes)
  :価格変更画面表示;
  :商品番号と新しい価格入力;
  :価格変更確認;
  :商品リスト更新;
else (3)
  :管理画面終了;
  :タイトル画面に戻る;
endif
stop
@enduml