@startwbs 券売機制作
title 管理者券売機
* 管理者
**[#Aqua] 売上計算
***[#Yellow] 売上金額
***[#Yellow]  総売上
**[#Aqua] 入力番号受け取り
***[#Yellow] キーボード入力
***[#Yellow] 管理コード判別
**[#Aqua] 管理者コード１の処理
***[#Yellow] 売上のリセット
**[#Aqua] 管理者コード２の処理
***[#Yellow] 売上リセット判別
***[#Yellow] 変更する商品の番号受け取り
***[#Yellow] 変更金額の受け取り
***[#Yellow] 再確認
**[#Aqua] コード３の処理
***[#Yellow] タイトル画面に戻る
**[#Aqua] 全体の文字
***[#Yellow] 商品表示
***[#Yellow] 結果表示
@endwbs

