@startuml
start
:タイトル画面表示;
:商品選択画面;
:商品番号と数量入力;
if (支払いに進むか？) then (yes)
  :購入商品確認画面;
  :合計金額の表示;
  :現金を投入;
  if (現金が足りているか？) then (yes)
    :購入完了;
    :お釣り表示;
    :タイトル画面に戻る;
  else (no)
    :金額不足メッセージ表示;
    :再度現金投入;
    if (現金が足りているか？) then (yes)
      :購入完了;
      :お釣り表示;
      :タイトル画面に戻る;
    else (no)
      :再度現金投入;
    endif
  endif
else (no)
  :再度商品選択;
  :商品選択画面;
endif
stop
@enduml
